name: dev_notebook
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.3

dev_dependencies:
  test: ^1.17.12
  flutter_linter:
    git: https://github.com/andrsem/flutter_linter
