name: dev_notebook
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  http: ^0.13.1

dev_dependencies:
  test: ^1.16.8
